// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFBpPjI0FPvZtF19uxXCJKGwsgZSFR9-A',
    appId: '1:645084179140:web:6408c8dec8f53d6d157791',
    messagingSenderId: '645084179140',
    projectId: 'groceryapp-d7327',
    authDomain: 'groceryapp-d7327.firebaseapp.com',
    storageBucket: 'groceryapp-d7327.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGCqp0mQij8MVUBgd_s30w7wzmJ1GmyC8',
    appId: '1:645084179140:android:c24851677158203e157791',
    messagingSenderId: '645084179140',
    projectId: 'groceryapp-d7327',
    storageBucket: 'groceryapp-d7327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUCVIdUCeSzY3NHAFK1ru-ISUST4SjsvA',
    appId: '1:645084179140:ios:1e446f24a41deab8157791',
    messagingSenderId: '645084179140',
    projectId: 'groceryapp-d7327',
    storageBucket: 'groceryapp-d7327.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUCVIdUCeSzY3NHAFK1ru-ISUST4SjsvA',
    appId: '1:645084179140:ios:1e446f24a41deab8157791',
    messagingSenderId: '645084179140',
    projectId: 'groceryapp-d7327',
    storageBucket: 'groceryapp-d7327.firebasestorage.app',
    iosBundleId: 'com.example.groceryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFBpPjI0FPvZtF19uxXCJKGwsgZSFR9-A',
    appId: '1:645084179140:web:d7249e962b0b4512157791',
    messagingSenderId: '645084179140',
    projectId: 'groceryapp-d7327',
    authDomain: 'groceryapp-d7327.firebaseapp.com',
    storageBucket: 'groceryapp-d7327.firebasestorage.app',
  );
}
